// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// int50hz //
// ------- //

#define int50hz_wrap_target 1
#define int50hz_wrap 4

static const uint16_t int50hz_program_instructions[] = {
    0x80a0, //  0: pull   block                      
            //     .wrap_target
    0xe001, //  1: set    pins, 1                    
    0xe000, //  2: set    pins, 0                    
    0xa027, //  3: mov    x, osr                     
    0x0044, //  4: jmp    x--, 4                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program int50hz_program = {
    .instructions = int50hz_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config int50hz_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + int50hz_wrap_target, offset + int50hz_wrap);
    return c;
}

// Loop value less non-looping cycles to total 4096
#define INT50HZ_LOOP (4095-3)
static inline void int50hz_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = int50hz_program_get_default_config(offset);
    // 50 Hz clock over 4096 cycles
    float clk50hz = (float)clock_get_hz(clk_sys) / (50.0*4096.0);
    sm_config_set_clkdiv(&c, clk50hz);
    // Configure 1 ouptut pin for use with "set"
    sm_config_set_set_pins(&c, pin, 1);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif
